<?php
$active_group = 'default';
$active_record = TRUE;
$db['default']['username'] = 'ugnnFEPZmETyz';
$db['default']['password'] = 'p1cgfZFdAOoR2';
$db['default']['hostname'] = 'eu01-user01.cbxizyg0fwcn.eu-west-1.rds.amazonaws.com';
$db['default']['database'] = 'df66208251b404569860e4bfa10a312ae';
$db['default']['dbdriver'] = 'mysqli';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = FALSE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
/* Autogenerated Configuration for db 2015-03-30 */
